#!/bin/bash
echo "##############################"
echo "# Native library dependancy  #"
echo "##############################"
./initsubmodules
cd src/deps/tilengine/src
make all
cd ..
sudo ./install
sudo chmod 755 /usr/local/lib/libTilengine.so
cd src
