#!/bin/bash
echo "##############################"
echo "# Native library dependancy  #"
echo "##############################"
./initsubmodules
make src/deps/tilengine/src
cd src/deps/tilengine
./install
cd src
